jobs:
  repository-dispatch-event:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        client-payload: '{"username": "${{ github.actor }}", "release": ${{ toJSON(github.event.release)
          }}}'
        event-type: release-pinpoint
        repository: pinpoint-apm/pinpoint-apm.github.io
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
name: Homepage
on:
  repository_dispatch:
    types: trigger-ga___homepage.yml
